
<head>

<title>CVGweb</title>

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<!-- Keep the http-equiv meta tag for IE8 -->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- Link the CSS file here -->
<link rel="stylesheet" type="text/css" media="screen,projection" href="../pcvgcss/css_pcvgmenu01.css" />
<link rel="stylesheet" type="text/css" media="screen,projection" href="../pcvgcss/geral.css">

</head>

<body bgcolor="#E6EAE9" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<!-- Tabela principal -->
<table width="96%" border="0" cellspacing="0" cellpadding="0" height="12" align="center">

<!-- Tabela logo Embrapa -->
  <tr><td>
     <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
       <tr>
          <td><img src="../pcvgimg/embrapa04.bmp" border="0"></td>
       </tr>
       <tr>
          <td bgcolor="#ffffff"><img src="../pcvgnimg/clear.gif" width="1" height="1"></td>
       </tr>
     </table>
  </td></tr>
    
<!-- Tabela para barra azul superior -->
  <tr><td>
  <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
  <tr>
  <td><img src="../pcvgimg/cvgtitulo1.png" border="0"></td>
  <td width="6%"><a href="javascript:history.back();">
     <img border="0" src="../pcvgimg/retornar1.bmp"></a></td>
  </tr>
  </table>
  </td></tr>
 
 
<!-- Tabela menu de opções  -->
  <tr><td>
<!-- PULL DOWN MENU - BEGIN -->
      <div class="mainmenu">
         <ul>
            <li class="li_nc"><a href="../pcvghtml/pcvghome01.php" target="_self" >Página Principal</a></li>
            <li class="li_hc"><a href="#">Cadastro</a>
               <ul class="ul_ch">
                   <li class="li_hc"><a href="../pcvghtml/pcvgfuncionario.php">Funcionário</a></li>
                   <li class="li_hc"><a href="../pcvghtml/pcvgprojeto.php">Projeto</a></li>
                   <li class="li_hc"><a href="../pcvghtml/pcvgevento.php">Evento</a></li>
                   <li class="li_hc"><a href="../pcvghtml/pcvginstituicao.php">Instituição</a></li>   
               </ul>
            </li>
            <li class="li_hc"><a href="#">SGP</a>
               <ul class="ul_ch">
<!--                   <li class="li_hc"><a href="#">Folha de Ponto</a>
                       <ul class="ul_ch">
                           <li class="li_hc"><a href="../psgphtml/psgpfolhaponto.php">Gerenciamento (SGP)</a></li>
     		           <li class="li_hc"><a href="../psgphtml/psgpmeuponto.php">Meus Protocolos de Folhas de Ponto</a></li>
                       </ul>
                   </li>           -->
                   <li class="li_hc"><a href="#">Estagiários, bolsistas, etc</a>
                      <ul class="ul_ch">
                         <li class="li_hc"><a href="../psgphtml/psgpestagbolsista.php">Gerenciamento (restrito ao SGP)</a>
-                         <li class="li_hc"><a href="#">Meus estagiários, bolsistas, etc</a>
                          </li>
                      </ul>
                   </li>    
                   <li class="li_hc"><a href="#">Avaliação</a>
                      <ul class="ul_ch">
                         <li class="li_hc"><a href="#">Avaliação do Empregado >>></a>
                            <ul class="ul_ch">
      	   <!--                     <li class="li_hc"><a href="../jsgphtml/jsgpavacompet2011.jsp"> 2011 (ano base 2010)</a></li>  
     		                <li class="li_hc"><a href="../pa1112html/pa12avacompet2012.php"> 2012 (ano base 2011)</a></li>
     		                <li class="li_hc"><a href="../pa13html/pa13avacompet2013.php"> 2013 (ano base 2012)</a></li>            
     		                <li class="li_hc"><a href="../pa14html/pa14avacompet2014.php"> 2014 (ano base 2013)</a></li>         
     		                <li class="li_hc"><a href="../pa15html/pa15avacompet2015.php"> 2015 (ano base 2014)</a></li>               
     		                <li class="li_hc"><a href="../pa16html/pa16avacompet2016.php"> 2016 (ano base 2015)</a></li>   
     		                <li class="li_hc"><a href="../pa17html/pa17avacompet2017.php"> 2017 (ano base 2016)</a></li>   
    		                <li class="li_hc"><a href="../pa18html/pa18avacompet2018.php"> 2018 (ano base 2017)</a></li>  
    		                <li class="li_hc"><a href="../pa19html/pa19avacompet2019.php"> 2019 (ano base 2018)</a></li>      
    		                <li class="li_hc"><a href="../pa20html/pa20avacompet2020.php"> 2020 (ano base 2019)</a></li> 
    		                <li class="li_hc"><a href="../pa21html/pa21avacompet2021.php"> 2021 (ano base 2020)</a></li>   
    		                <li class="li_hc"><a href="../pa22html/pa22avacompet2022.php"> 2022 (ano base 2021)</a></li>   
    		                <li class="li_hc"><a href="../pa23html/pa23avacompet2023.php"> 2023 (ano base 2022)</a></li>  
                                <li class="li_hc"><a href="../pa24html/pa24avacompet2024.php"> 2024 (ano base 2023)</a></li>    -->
                                <li class="li_hc"><a href="../pa25html/pa25avacompet2025.php"> 2025 (ano base 2024)</a></li>
                            </ul>
                         </li>
                      </ul>
                   </li>
<!--                   <li class="li_hc"><a href="#">Marcação de Férias</a>
                       <ul class="ul_ch">
                           <li class="li_hc"><a href="../psgphtml/psgpferias.php">Gerenciamento (SGP)</a></li>
     		           <li class="li_hc"><a href="../psgphtml/psgpminhasferias.php">Minha marcação de férias</a></li>
     		           <li class="li_hc"><a href="../psgphtml/psgpferiassupervisionados.php">Férias - meus supervisionados</a></li>
                       </ul>
                   </li>                  -->
               </ul>
            </li>
<!--            <li class="li_hc"><a href="#">NCO</a>
               <ul class="ul_ch">
                   <li class="li_hc"><a href="../pncohtml/pncosolicitgraf.php">Agendamento com CHTT</a></li>
                   <li class="li_hc"><a href="../pncohtml/pncosolicitgraf.php">Agendamento com NCO</a></li>
                   <li class="li_hc"><a href="../pncohtml/pncosolicitgraf.php">Solicitação de serviços gráficos</a></li>
                   <li class="li_hc"><a href="../pncohtml/pncogerenciagraf.php">Gerenciamento de serviços gráficos</a></li>
               </ul>
            </li>        -->                    

<!---            <li class="li_hc"><a href="#">Auditório/Sala</a>
               <ul class="ul_ch">
                   <li class="li_hc"><a href="../pagdhtml/pagdagendamento.php">Agendamento de auditório/sala</a></li>
                   <li class="li_hc"><a href="../pagdhtml/pagdgerenciaaudsala.php">Gerenciamento de auditório/sala</a></li>
               </ul>
            </li>        -->                  
            
<!--            <li class="li_hc"><a href="#">Evento</a>
                <ul class="ul_ch">
                   <li class="li_hc"><a href="../pevthtml/pevtgerenciaevento.php">Gerenciamento (SGP)</a></li>
                   <li class="li_hc"><a href="../pevthtml/pevtpropevento.php">Proposta de evento</a></li>
                   <li class="li_hc"><a href="../pevthtml/pevtpreinscr01.php">Inscrição em eventos</a></li>
                </ul>
            </li>                 -->
            
<!--            <li class="li_hc"><a href="#">SCC</a>
               <ul class="ul_ch">
                   <li class="li_hc"><a href="#">Contratos/Convênios</a>
                       <ul class="ul_ch">
                           <li class="li_hc"><a href="../pscchtml/pscccontrole.php">Controle (SCC)</a></li>
     		           <li class="li_hc"><a href="../pscchtml/psccmeuscontratos.php">Meus contratos/convênios</a></li>   
                       </ul>
                   </li>
               </ul>
            </li>                                      
            
            <li class="li_hc"><a href="#">Campos Experimentais</a>
               <ul class="ul_ch">
                   <li class="li_hc"><a href="../pcpdhtml/pcpdcamposexp.php">Atualizar</a></li>
                   <li class="li_hc"><a href="../pcpdhtml/pcpdatribareas.php">Atributos de áreas</a></li>
                   <li class="li_hc"><a href="../pcpdhtml/pcpdcons01.php?op=9">Consultar</a></li>
               </ul>
            </li>                                              -->
            <li class="li_hc"><a href="#">Administração</a>
               <ul class="ul_ch">
                   <li class="li_nc"><a href="../psgphtml/psgpperfilusr.php">Perfil de Usuário CEN<i>web</i></a></li>  -->
<!--                   <li class="li_nc"><a href="../psgphtml/psgpimportferias.php">Importar marcação de férias</a></li>  
               </ul>
            </li>
         </ul>
      </div>
<!-- END OF PULL DOWN MENU -->
  </td></tr>

<!-- =================================================== -->  		  
<!-- ***** TABELA CENTRO (ÁREA DE DESENVOLVIMENTO) ***** -->  		  
<!-- =================================================== -->  		  
  <tr><td>

