<!-- ========================================================== -->  		  
<!-- ***** Fim da TABELA CENTRO (AREA DE DESENVOLVIMENTO) ***** -->  		  
<!-- ========================================================== -->  		  
  </td></tr>

</table> 	   

<!-- Tabela para barra azul inferior-->  
<table width="96%" bgcolor="#0000FF" border="0" cellspacing="0" 
 cellpadding="4" height="20" align="center">
<tr>
<td background="../pcenimg/cvg_bg.bmp" border="0">
  <div align="center">
    <font face="Verdana" size="1" color="White">
        <b>CVG<i>web</i> - Versão 001 - Embrapa Recursos Genéticos e Biotecnologia</b>
    </font>
  </div>
</td>
</tr>
</table>
</td>
</tr>
</table>

</body>
