
<head>

<title>CVGweb</title>

<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<!-- Keep the http-equiv meta tag for IE8 -->
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<!-- Link the CSS file here -->
<link rel="stylesheet" type="text/css" media="screen,projection" href="../pcvgcss/css_pcvgmenu01.css" />
<link rel="stylesheet" type="text/css" media="screen,projection" href="../pcvgcss/geral.css">

</head>

<body bgcolor="#E6EAE9" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<!-- Tabela principal -->
<table width="96%" border="0" cellspacing="0" cellpadding="0" height="12" align="center">

<!-- Tabela logo Embrapa -->
  <tr><td>
     <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
       <tr>
          <td><img src="../pcvgimg/embrapa04.bmp" border="0"></td>
       </tr>
       <tr>
          <td bgcolor="#ffffff"><img src="../pcvgimg/clear.gif" width="1" height="1"></td>
       </tr>
     </table>
  </td></tr>
    
<!-- Tabela para barra azul superior -->
  <tr><td>
  <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
  <tr>
  <td><img src="../pcvgimg/cvgtitulo1.png" border="0"></td>
  <td width="6%"><a href="javascript:history.back();">
     <img border="0" src="../pcvgimg/retornar1.bmp"></a></td>
  </tr>
  </table>
  </td></tr>
 
 
<!-- Tabela menu de opções  -->
  <tr><td>
<!-- PULL DOWN MENU - BEGIN -->
      <div class="mainmenu">
         <ul>
            <li class="li_nc"><a href="../pcvghtml/pcvghome01.php" target="_self" >Retornar à Página Principal</a></li>
         </ul>
      </div>
<!-- END OF PULL DOWN MENU -->
  </td></tr>

<!-- =================================================== -->  		  
<!-- ***** TABELA CENTRO (ÁREA DE DESENVOLVIMENTO) ***** -->  		  
<!-- =================================================== -->  		  
  <tr><td>

