<!-- Tabela principal -->
<table width="96%" border="0" cellspacing="0" cellpadding="0" height="12" align="center">

<!-- Tabela logo Embrapa -->
  <tr><td>
     <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
       <tr>
          <td><img src="../pcvgimg/embrapa04.bmp" border="0"></td>
       </tr>
       <tr>
          <td bgcolor="#ffffff"><img src="../pcvgimg/clear.gif" width="1" height="1"></td>
       </tr>
     </table>
  </td></tr>
    
<!-- Tabela para barra azul superior -->
  <tr><td>
  <table border="0" width="100%" bgcolor="#0000FF" border="0" cellspacing="0" cellpadding="4" height="20" align="center">
  <tr>
  <td><img src="../pcvgimg/cvgtitulo1.png" border="0"></td>
  <td width="6%"><a href="javascript:history.back();">
     <img border="0" src="../pcvgimg/retornar1.bmp"></a></td>
  </tr>
  </table>
  </td></tr>
 
 
<!-- Tabela menu de opções  -->
  <tr><td>
<!-- PULL DOWN MENU - BEGIN -->
      <div class="mainmenu">
         <ul>
            <li class="li_nc"><a href="../pcvghtml/pcvgmenuopcoes.php?op=continua&tipo=1" target="_self" >Retornar ao menu de opções</a></li>
         </ul>
      </div>
<!-- END OF PULL DOWN MENU -->
  </td></tr>

<!-- =================================================== -->  		  
<!-- ***** TABELA CENTRO (ÁREA DE DESENVOLVIMENTO) ***** -->  		  
<!-- =================================================== -->  		  
  <tr><td>
