   <html>
   <body>
   <?php require ("pcvgCABEC07.inc") ?>
   <center>
   <h3>Acesso restrito à esta página</h3>
   <p>
   <h3>Clique no botão abaixo para ir para a página inicial do sistema</h3>
   <form method="post" action="../pcvghtml/pcvghome01.php">
   <input type="Submit" value="Página Inicial do Sistema">
   </form>
   <p>
   </center>
   <?php require ("pcvgRODAPE01.inc") ?>
   </body>
   </html>
